services:
  init-postgres:
    image: ${GUACAMOLE_IMAGE}

    volumes:
      - ./volumes/postgres/init:/tmp/postgres-init

    command: >
      /bin/sh -c 'set -ex;
      if [ ! -f /tmp/postgres-init/initdb.sql ]; then
        /opt/guacamole/bin/initdb.sh --postgresql >/tmp/postgres-init/initdb.sql;
      fi'

  postgres:
    image: postgres

    networks: ["guacamole"]
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/postgres/init:/docker-entrypoint-initdb.d
      - ./volumes/postgres/data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 3s
    depends_on:
      init-postgres:
        condition: service_completed_successfully
    restart: unless-stopped

  guacd:
    image: ${GUACD_IMAGE}

    networks: ["guacamole"]

    restart: unless-stopped

  guacamole:
    image: ${GUACAMOLE_IMAGE}

    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_USER: postgres
    network_mode: service:tailscale

    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale
    
    cap_add: ["net_admin"]
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: false
    hostname: guacamole
    networks: ["guacamole"]
    volumes:
      - ./volumes/tailscale/state:/var/lib/tailscale

    restart: unless-stopped

networks:
  guacamole:
